services:
  - type: web
    name: datn-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: Firebase__ProjectId
        value: datndoanhdd
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false   # <- mày điền tay trong Render dashboard (nội dung file JSON)
